const Images = {
  Logo: new URL("./Logo.svg", import.meta.url).href,
  Logo2: new URL("./Logo2.svg", import.meta.url).href,
  acaibowl: new URL("./acaibowl.jpg", import.meta.url).href,
  avocadotoast: new URL("./avocadotoast.jpg", import.meta.url).href,
  bananapancakes: new URL("./bananapancakes.jpg", import.meta.url).href,
  blueberryfrenchtoast: new URL("./blueberryfrenchtoast.jpg", import.meta.url)
    .href,
  breakfastspread: new URL("./breakfastspread.jpg", import.meta.url).href,
  chickenwaffles: new URL("./chickenwaffles.jpg", import.meta.url).href,
  crepes: new URL("./crepes.jpg", import.meta.url).href,
  DanishPancakes: new URL("./DanishPancakes.jpg", import.meta.url).href,
  eggbenedict: new URL("./eggbenedict.jpg", import.meta.url).href,
  exterior: new URL("./exterior.jpg", import.meta.url).href,
  fruitpancake: new URL("./fruitpancake.jpg", import.meta.url).href,
  gathering: new URL("./gathering.jpg", import.meta.url).href,
  gathering2: new URL("./gathering2.jpg", import.meta.url).href,
  globe: new URL("./globe.jpg", import.meta.url).href,
  granola: new URL("./granola.jpg", import.meta.url).href,
  granola2: new URL("./granola2.jpg", import.meta.url).href,
  greenrestaurant: new URL("./greenrestaurant.jpg", import.meta.url).href,
  parfait: new URL("./parfait.jpg", import.meta.url).href,
  shakshouka: new URL("./shakshouka.jpg", import.meta.url).href,
  spread1: new URL("./spread1.jpg", import.meta.url).href,
  spread2: new URL("./spread2.jpg", import.meta.url).href,
  spread3: new URL("./spread3.jpg", import.meta.url).href,
  spread4: new URL("./spread4.jpg", import.meta.url).href,
  steakandeggs: new URL("./steakandeggs.png", import.meta.url).href,
  sweettoast: new URL("./sweettoast.jpg", import.meta.url).href,
  travel: new URL("./travel.png", import.meta.url).href,
  travelfood: new URL("./travelfood.jpg", import.meta.url).href,
  travelfood2: new URL("./travelfood2.jpg", import.meta.url).href,
};

export default Images;
